name: Git Notifications

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, labeled, unlabeled]

jobs:
  notify_slack:
    runs-on: windows-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: rtCamp/action-slack-notify@v3
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          fields: repo,message,commit,author,action
