name: Git Notifications

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, labeled, unlabeled]

jobs:
  notify_slack:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          message: |
            Job Status: ${{ job.status }}
            Author: ${{ github.actor }}
            Event: ${{ github.event_name }}
            Repository: ${{ github.repository }}
            Commit Message: ${{ github.event.head_commit.message }}
